version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=graphql
    ports:
      - "5432:5432"
    restart: always
